### ISSUE TITLE
[Metadata] Flathub uses old Plasma 4 / Oxygen icon

### ISSUE THREAD

**Issue by ghost** [flathub/org.kde.yakuake#13]
Compare the icons in the top left corners:

https://flathub.org/apps/org.kde.yakuake (blue, gray, and white Oxygen icon)

https://apps.kde.org/yakuake/ (black, gray, and blue Breeze icon)

**Comment by travier** [comment]
https://invent.kde.org/utilities/yakuake/-/merge_requests/125
